server:
  port: 8082 # 数据处理模块服务端口

spring:
  application:
    name: data-processing-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/datadb
    username: user
    password: password

spring.cloud.stream:
  bindings:
    input:
      destination: data-topic
      group: data-processing-group
    output:
      destination: result-topic

management:
  endpoints:
    web:
      exposure:
        include: "*"
