server:
  port: 8003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: nacos
          uri: https://192.168.56.1:8001/nacos
          predicates:
            - Path=/nacos
        - id: config
          uri: https://192.168.56.1:8002/config
          predicates:
            - Path=/config