spring:
  application:
    name: user-service
  resilience4j:
    circuitbreaker:
      instances:
        default:
          # 定义熔断器的失败率阈值为 50%
          failure-rate-threshold: 50
          # 配置窗口大小为 10 请求，统计期间为 1 秒
          sliding-window-size: 10
          # 设置熔断器开启时的等待时间
          wait-duration-in-open-state: 1000ms
          # 超过次数后触发熔断
          permitted-number-of-calls-in-half-open-state: 3
          # 配置请求的超时时间（如果需要）
          timeout-duration: 500ms

    feign:
      hystrix:
        enabled: false
  management:
    endpoints:
      web:
        exposure:
          include: "health", "metrics", "circuitbreakers"
