spring:
  shardingsphere:
    datasource:
      names: primary,replica
      replica:
        url: jdbc:sqlite:D:/work/code/Others/atabase/sqlite/base.db
        driver-class-name: org.sqlite.JDBC
      primary:
        url: jdbc:postgresql://192.168.1.3:5432/lkxl
        driver-class-name: org.postgresql.Driver
        username: wnlhdx
        password: w1995520
      readwrite-splitting:
        dataSources:
          master:
            dataSourceName: primary
          slave:
            dataSourceNames:
              - replica
        loadBalanceAlgorithmType: ROUND_ROBIN  # 负载均衡策略，默认轮询
        rule:
          type: READWRITE_SPLITTING

  datasource:
    names: primary,replica
    replica:
      url: jdbc:sqlite:/data/data/com.termux/files/home/myfolder/Git/Others/database/sqlite/base.db
      driver-class-name: org.sqlite.JDBC
    primary:
      url: jdbc:postgresql://192.168.1.3:5432/lkxl
      driver-class-name: org.postgresql.Driver
      username: wnlhdx
      password: w1995520
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
  data:
    redis:
      host: 192.168.1.3
      port: 6379
      password: null
      jedis:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 3000
      timeout: 2000
  rabbitmq:
    host: 192.168.1.3
    port: 5672
    username: wnlhdx
    password: w1995520
    virtual-host: /
    listener:
      simple:
        acknowledge-mode=manual: manual

    # Quartz配置
  quartz:
    job-store-type : jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          tablePrefix: QRTZ_
          isClustered: true
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 10
server:
  port: 8080