spring:
  shardingsphere:
    datasource:
      names: primary,replica
      replica:
        url: jdbc:sqlite:D:/work/code/Others/atabase/sqlite/base.db
        driver-class-name: org.sqlite.JDBC
      primary:
        url: jdbc:postgresql://192.168.1.3:5432/lkxl
        driver-class-name: org.postgresql.Driver
        username: wnlhdx
        password: w1995520
      readwrite-splitting:
        dataSources:
          master:
            dataSourceName: primary
          slave:
            dataSourceNames:
              - replica
        loadBalanceAlgorithmType: ROUND_ROBIN  # 负载均衡策略，默认轮询
        rule:
          type: READWRITE_SPLITTING