spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
     username: root
     password: w1995520
     driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/TestMapping.xml
server:
  port: 8888
logging:
　　config: classpath:log4j2.yaml