spring:
  datasource:
     url: jdbc:mysql://192.168.1.2:3306/test?useUnicode=true&characterEncoding=utf8
     username: wnlhdx
     password: w1995520
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.myproject.springboot.entity
server:
  port: 8080
logging:
  config: classpath:log4j2.yaml
  level:
    org:
      mybatis=DEBUG:

