server:
  port: 9090

spring:
  application:
    name: monitoring-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

spring.sleuth:
  sampler:
    probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    enabled: true

logging:
  level:
    org.springframework: DEBUG
